//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcingaWebServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mkaminski.mgr/", ConfigurationName="IcingaWebServiceRef.IcingaWebService")]
    public interface IcingaWebService {
        
        // CODEGEN: Parameter 'checks' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IcingaWebServiceRef.processChecksResponse processChecks(IcingaWebServiceRef.processChecksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IcingaWebServiceRef.processChecksResponse> processChecksAsync(IcingaWebServiceRef.processChecksRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mkaminski.mgr/")]
    public partial class Check : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hostNameField;
        
        private string serviceNameField;
        
        private double resultField;
        
        private long timestampField;
        
        private string stateField;
        
        private bool hasExceededField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string hostName {
            get {
                return this.hostNameField;
            }
            set {
                this.hostNameField = value;
                this.RaisePropertyChanged("hostName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string serviceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("serviceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool hasExceeded {
            get {
                return this.hasExceededField;
            }
            set {
                this.hasExceededField = value;
                this.RaisePropertyChanged("hasExceeded");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processChecks", WrapperNamespace="http://mkaminski.mgr/", IsWrapped=true)]
    public partial class processChecksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("checks", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public IcingaWebServiceRef.Check[] checks;
        
        public processChecksRequest() {
        }
        
        public processChecksRequest(IcingaWebServiceRef.Check[] checks) {
            this.checks = checks;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processChecksResponse", WrapperNamespace="http://mkaminski.mgr/", IsWrapped=true)]
    public partial class processChecksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public processChecksResponse() {
        }
        
        public processChecksResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IcingaWebServiceChannel : IcingaWebServiceRef.IcingaWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IcingaWebServiceClient : System.ServiceModel.ClientBase<IcingaWebServiceRef.IcingaWebService>, IcingaWebServiceRef.IcingaWebService {
        
        public IcingaWebServiceClient() {
        }
        
        public IcingaWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IcingaWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcingaWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcingaWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IcingaWebServiceRef.processChecksResponse IcingaWebServiceRef.IcingaWebService.processChecks(IcingaWebServiceRef.processChecksRequest request) {
            return base.Channel.processChecks(request);
        }
        
        public string processChecks(IcingaWebServiceRef.Check[] checks) {
            IcingaWebServiceRef.processChecksRequest inValue = new IcingaWebServiceRef.processChecksRequest();
            inValue.checks = checks;
            IcingaWebServiceRef.processChecksResponse retVal = ((IcingaWebServiceRef.IcingaWebService)(this)).processChecks(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IcingaWebServiceRef.processChecksResponse> IcingaWebServiceRef.IcingaWebService.processChecksAsync(IcingaWebServiceRef.processChecksRequest request) {
            return base.Channel.processChecksAsync(request);
        }
        
        public System.Threading.Tasks.Task<IcingaWebServiceRef.processChecksResponse> processChecksAsync(IcingaWebServiceRef.Check[] checks) {
            IcingaWebServiceRef.processChecksRequest inValue = new IcingaWebServiceRef.processChecksRequest();
            inValue.checks = checks;
            return ((IcingaWebServiceRef.IcingaWebService)(this)).processChecksAsync(inValue);
        }
    }
}
